### ISSUE TITLE
Convert map markers to use icons

### ISSUE THREAD

**Issue by lshadler** [lshadler/roost#1]
[Material UI React Icons](https://www.npmjs.com/package/@material-ui/icons)

[Font Icons](https://material-ui.com/components/icons/#icon-font-icons)

To save space on the map, let's collapse the view using Icons

Rough vision:

- a set of 5 icon types chosen
- the data set has a new attribute `icon` that has the icon name
- render `<Icon>{icon}</Icon>` in collapsed view

- split chosen icon names to roughly symbolize types of business

**Comment by steebe** [comment]
My five:

1. import LocalCafeIcon from '@material-ui/icons/LocalCafe';
![image](https://user-images.githubusercontent.com/22264597/77219646-1f799f80-6b0e-11ea-9814-1602025ec928.png)

2. import FastfoodIcon from '@material-ui/icons/Fastfood';
![image](https://user-images.githubusercontent.com/22264597/77219627-0bce3900-6b0e-11ea-9d4c-bcccd682b1ad.png)

3. import LocalDiningIcon from '@material-ui/icons/LocalDining';
![image](https://user-images.githubusercontent.com/22264597/77219725-b0e91180-6b0e-11ea-9c9a-c6ba54b26847.png)

4. import LocalBarIcon from '@material-ui/icons/LocalBar';
![image](https://user-images.githubusercontent.com/22264597/77219737-c4947800-6b0e-11ea-840f-bede5a0ef585.png)

5. import LocalConvenienceStoreIcon from '@material-ui/icons/LocalConvenienceStore';
![image](https://user-images.githubusercontent.com/22264597/77219765-21902e00-6b0f-11ea-9617-26e7b7923e70.png)

**Comment by steebe** [comment]
6. import StoreIcon from '@material-ui/icons/Store';
![image](https://user-images.githubusercontent.com/22264597/77219858-20133580-6b10-11ea-896e-f4ed0dca0d10.png)

**Comment by steebe** [comment]
https://material-ui.com/components/material-icons/ for reference 😄
